# Generated by Django 5.2.1 on 2025-05-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='fournisseur',
            new_name='nom_fournisseur',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='fournisseur_site',
        ),
    ]
